### PR TITLE
Multiple changes.

### PR DESCRIPTION
**Pull request by ghost**
* Add "Lab Activities" header so that the lab activity items are not
  the content of the "Outcomes" section.
* Where phrases are complete sentences, add period.
* Use minimum number of backticks necessary to trigger correct code
  block formatting.
* Add newlines between activity items to improve readability while
  working on lab.
* Slight phrasing tweaks in a couple places.
* MariaDB install should be "mariadb-server" not "mariadb".

### CODE REVIEW

**Comment by ghost** [comment]
NOTE: I realize I used "re-nice" in the nice activity because that's how I performed that action and that that may not be your intent. Feel free to ignore that change or modify as you see fit.

**Comment by ghost** [comment]
Suggestion regarding questions 12 & 13: Just as question 11 is "do something the old way and then do it the new systemctl way", questions 12 and 13 could be merged together since this is the same type of activity.

**Comment by ghost** [comment]
Questions 10 & 23 should be combined because they overlap significantly.

**Comment by jhajek** [comment]
Wow -- thanks for the material.  I think it all looks reasonable.  I'll merge it.

**Pull request merged**
